import type { Metadata } from "next";
import "./globals.css";
  import { Geist } from 'next/font/google';


export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by Varcel",
};

const geist = Geist({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  cz-shortcut-listen="true" className={geist.className} >
        {children}
      </body>
    </html>
  );
}
